# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(341, 511)
        self.start = QtWidgets.QPushButton(Dialog)
        self.start.setGeometry(QtCore.QRect(10, 430, 101, 41))
        self.start.setObjectName("start")
        self.clear = QtWidgets.QPushButton(Dialog)
        self.clear.setGeometry(QtCore.QRect(120, 430, 101, 41))
        self.clear.setObjectName("clear")
        self.submit = QtWidgets.QPushButton(Dialog)
        self.submit.setGeometry(QtCore.QRect(230, 430, 101, 41))
        self.submit.setObjectName("submit")
        self.groupBox1 = QtWidgets.QGroupBox(Dialog)
        self.groupBox1.setGeometry(QtCore.QRect(10, 10, 181, 321))
        self.groupBox1.setObjectName("groupBox1")
        self.Question = QtWidgets.QTextBrowser(self.groupBox1)
        self.Question.setGeometry(QtCore.QRect(10, 20, 161, 291))
        self.Question.setObjectName("Question")
        self.groupBox2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox2.setGeometry(QtCore.QRect(200, 10, 131, 321))
        self.groupBox2.setObjectName("groupBox2")
        self.Answer = QtWidgets.QTextEdit(self.groupBox2)
        self.Answer.setGeometry(QtCore.QRect(10, 20, 111, 291))
        self.Answer.setObjectName("Answer")
        self.myname = QtWidgets.QPushButton(Dialog)
        self.myname.setGeometry(QtCore.QRect(10, 480, 321, 23))
        self.myname.setObjectName("myname")
        self.Timer = QtWidgets.QTextBrowser(Dialog)
        self.Timer.setGeometry(QtCore.QRect(20, 340, 301, 81))
        self.Timer.setObjectName("Timer")
        self.Timer.setStyleSheet("text-align: center; font-size: 48pt; line-height: 81px; color: rgb(255, 0, 0)")

        self.retranslateUi(Dialog)
        self.myname.clicked.connect(Dialog.showName)
        self.clear.clicked.connect(Dialog.clear)
        self.start.clicked.connect(Dialog.layProblem)
        self.submit.clicked.connect(Dialog.checkAnswers)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "数算小游戏"))
        self.start.setText(_translate("Dialog", "开始"))
        self.clear.setText(_translate("Dialog", "清空"))
        self.submit.setText(_translate("Dialog", "提交"))
        self.groupBox1.setTitle(_translate("Dialog", "问题"))
        self.groupBox2.setTitle(_translate("Dialog", "答案"))
        self.myname.setText(_translate("Dialog", "作者:Handy_Wote"))
